---
title: "Educational Data Science Capstone Project"
runtime: shiny  
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: scroll
    theme: united
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(tidyverse)
library(here)
library(janitor)
library(rio)
library(colorblindr)
library(gghighlight)
library(forcats)
library(ggrepel)
library(gt)
library(knitr)
library(kableExtra)
library(reactable)
library(plotly)
library(glue)
library(fs)
library(rstatix)
library(ggpubr)
library(writexl)
library(remotes)

theme_set(theme_minimal(15) +
            theme(legend.position = "bottom",
                  panel.grid.major.x = element_line(color = "gray60"),
                  panel.grid.minor.x = element_blank(),
                  panel.grid.major.y = element_blank())
          )
```

```{r global, include=FALSE}
# all impact data 

impact_all <- read_csv(here("data", "impact_data.csv"))

str(impact_all)


#all clean sims data
sims_concussion_data <- read_csv(here("data", "sims_concussion_data.csv"))

str(sims_concussion_data)

sims_concussion_data <- sims_concussion_data %>% 
  mutate(age = as.factor(age))

str(sims_concussion_data)

#impact data only

one_impact_test <- read_csv(here("data", "one_post_injury_impact_test.csv"))

str(one_impact_test)

two_impact_test <- read_csv(here("data", "two_post_injury_impact_test.csv"))

three_impact_test <- read_csv(here("data", "three_post_injury_impact_test.csv"))

four_impact_test <- read_csv(here("data", "four_post_injury_impact_test.csv"))

# impact sims merge data

one_impact_sims <- read_csv(here("data", "one_post_injury_test_impact_sims_merge.csv"))

str(one_impact_sims)

two_impact_sims <- read_csv(here("data", "two_post_injury_test_impact_sims_merge.csv"))

three_impact_sims <- read_csv(here("data", "three_post_injury_test_impact_sims_merge.csv"))

four_impact_sims <- read_csv(here("data", "four_post_injury_test_impact_sims_merge.csv"))

# pcss items 

pcss_items <- import(here("data", "pcss_items.xlsx"),
               setclass = "tbl_df") 

pcss_cluster <- import(here("data", "cluster_scores.xlsx"),
               setclass = "tbl_df") 
```


# Data Overview 

Sidebar {.sidebar}
------------

**SIMS Data Variable Exploration**

```{r, include=TRUE}
selectInput("var1", "Total Concussion Plots:",
            choices = c("Gender" = "gender",
                        "Age" = "age",
                        "League" = "league",
                        "Sport Level" = "level"))

selectInput("var2", "Total Concussion Tables:",
            choices = c("School" = "school",
                        "Sport" = "sport"))

```


**SIMS RTL/RTP information**

```{r, inlcude=TRUE}

selectInput("bins1", "Number of Bins",
            choices = c(10, 25, 40, 55), selected = 25)

selectInput("var3", "RTL/RTP Tables:",
            choices = c("Gender" = "gender",
                        "Age" = "age",
                        "League" = "league",
                        "School" = "school",
                        "Sport" = "sport",
                        "Sport Level" = "level"))

```

Row {.tabset}
-----------------------------------------------------------------------

### Concussion Totals 1

```{r}
# Define inputs 

renderPlotly({
  sims_concussion_data %>%
    ggplot(aes_string(input$var1)) +
    geom_bar(fill = "blue",
             alpha = 0.7) +
    coord_flip() +
    labs(x = "",
         y = "Total Concussions")
})

```

### Concussion Totals 2

```{r, include=FALSE}
tbl_1 <- reactive({
  sims_concussion_data %>%
  group_by_at({{input$var2}}) %>%
  summarize(total = n()) %>%
  arrange(desc(total)) %>%
  reactable(
    defaultColDef = colDef(align = "center"),
    columns = list(
      total = colDef(name = "Total",
                     format = colFormat(suffix = " concussions"))),
    pagination = TRUE,
    striped = TRUE,
    outlined = TRUE,
    compact = TRUE,
    highlight = TRUE,
    bordered = TRUE
    )
  })
```

```{r, include=TRUE}
 renderReactable(tbl_1())
```


Row {.tabset}
-----------------------------------------------------------------------

### RTL 1

```{r, include=TRUE}
renderPlotly({
  sims_concussion_data %>% 
    ggplot(aes(dys_btwn_onset_rtp_3)) +
    geom_histogram(bins = input$bins1,
                   fill = "#56B4E9",
                color = "white",
                alpha = 0.9) +
    facet_wrap(input$var1) +
    labs(x = "Days to Complete RTL",
         y = "")
})
```

### RTL 2

```{r, include=FALSE}
rtl_tbl <- reactive({
  sims_concussion_data %>%
  group_by_at({{input$var3}}) %>%
  summarize(Mean = mean(dys_btwn_onset_rtp_3),
            SD = sd(dys_btwn_onset_rtp_3),
            Min = min(dys_btwn_onset_rtp_3),
            Max = max(dys_btwn_onset_rtp_3),
            Total = length(dys_btwn_onset_rtp_3)) %>% 
    arrange(desc(Total)) %>% 
    mutate_if(is.numeric, round, 2) %>% 
    reactable(
      defaultColDef = colDef(align = "center"),
      columns = list(
      Mean = colDef(format = colFormat(separators = TRUE, suffix = " days")),
      SD = colDef(format = colFormat(separators = TRUE, suffix = " days")),
      Min = colDef(format = colFormat(separators = TRUE, suffix = " days")),
      Max = colDef(format = colFormat(separators = TRUE, suffix = " days")),
      Total = colDef(format = colFormat(separators = TRUE, suffix = " concussions"))  
      ),
    pagination = TRUE,
    striped = TRUE,
    outlined = TRUE,
    compact = TRUE,
    highlight = TRUE,
    bordered = TRUE
    )
  })
```

```{r, include=TRUE}
 renderReactable(rtl_tbl())
```

### RTP 1

```{r, include=TRUE}
renderPlotly({
  sims_concussion_data %>% 
    ggplot(aes(dys_btwn_onset_rtp_7)) +
    geom_histogram(bins = input$bins1,
                   fill = "#56B4E9",
                color = "white",
                alpha = 0.9) +
    facet_wrap(input$var1) +
    labs(x = "Days to Complete RTP",
         y = "")
})
```

### RTP 2

```{r, include=FALSE}
rtp_tbl <- reactive({
  sims_concussion_data %>%
  group_by_at({{input$var3}}) %>%
  summarize(Mean = mean(dys_btwn_onset_rtp_7),
            SD = sd(dys_btwn_onset_rtp_7),
            Min = min(dys_btwn_onset_rtp_7),
            Max = max(dys_btwn_onset_rtp_7),
            Total = length(dys_btwn_onset_rtp_7)) %>% 
    arrange(desc(Total)) %>% 
    mutate_if(is.numeric, round, 2) %>% 
    reactable(
      defaultColDef = colDef(align = "center"),
      columns = list(
      Mean = colDef(format = colFormat(separators = TRUE, suffix = " days")),
      SD = colDef(format = colFormat(separators = TRUE, suffix = " days")),
      Min = colDef(format = colFormat(separators = TRUE, suffix = " days")),
      Max = colDef(format = colFormat(separators = TRUE, suffix = " days")),
      Total = colDef(format = colFormat(separators = TRUE, suffix = " concussions"))  
      ),
    pagination = TRUE,
    striped = TRUE,
    outlined = TRUE,
    compact = TRUE,
    highlight = TRUE,
    bordered = TRUE
    )
  })
```

```{r, include=TRUE}
 renderReactable(rtp_tbl())
```

